### ISSUE TITLE
How to set level or couch db?

### ISSUE THREAD

**Issue by nkaramolegos** [kfsoftware/hlf-operator#41] opened 2022-02-01 11:10 UTC
How can I set the desired database?

**Comment by dviejokfs** [comment] 2022-02-01 21:55
Hi @nkaramolegos 

You can configure couchdb by setting the following property in the yaml:
```yaml
  couchdb:
    externalCouchDB: null
    password: couchdb
    user: couchdb
```

And then setting the stateDb property to `couchdb`:

```yaml
stateDb: couchdb
```

When creating the peer, you can pass the `--statedb` flag with the value `couchdb` in order to create a peer with CouchDB instead of leveldb. Note that you cannot switch the state database for an existing peer, if you want to switch to couchdb you must create new peers.

[https://hyperledger-fabric.readthedocs.io/en/release-2.3/couchdb_as_state_database.html](https://hyperledger-fabric.readthedocs.io/en/release-2.3/couchdb_as_state_database.html)

![image](https://user-images.githubusercontent.com/84456338/152058020-ad9d2bb3-29b4-444c-afaa-8ba2c48d7b4a.png)

**Comment by nkaramolegos** [comment] 2022-02-03 15:51
thank you. Can you specify the yaml file? Is  [this](https://github.com/kfsoftware/hlf-operator/blob/f3031be61c6b0a14265251c48bc5a8eddf8596d3/charts/hlf-peer/values.yaml) one?

Also, which are the yaml files for the configuration of the peers, orderer etc?

**Comment by dviejokfs** [comment] 2022-02-03 16:20
Hi @nkaramolegos 
Those values are used for the internal helm chart that is used by the operator, and these values are just the default ones, the real ones are set in the operator.

The operator parameters are specified with a CRD, for example, this would be a CRD used to deploy a peer:
```yaml
apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricPeer
metadata:
  labels:
    dc: dc1
    mspID: KFSMSP
  name: peer0-kfsmsp
  namespace: hlf
spec:
  couchDBexporter:
    enabled: true
    image: gesellix/couchdb-prometheus-exporter
    imagePullPolicy: IfNotPresent
    tag: v30.0.0
  couchdb:
    password: couchdb
    user: couchdb
  discovery:
    period: 60s
    touchPeriod: 60s
  dockerSocketPath: ''
  externalBuilders:
    - name: external-builder
      path: /builders/external-service
      propagateEnvironment: []
    - name: external-k8s-builder
      path: /builders/golang
      propagateEnvironment:
        - CHAINCODE_SHARED_DIR
        - FILE_SERVER_BASE_IP
        - KUBERNETES_SERVICE_HOST
        - KUBERNETES_SERVICE_PORT
        - K8SCC_CFGFILE
        - TMPDIR
        - LD_LIBRARY_PATH
        - LIBPATH
        - PATH
        - EXTERNAL_BUILDER_HTTP_PROXY
        - EXTERNAL_BUILDER_HTTPS_PROXY
        - EXTERNAL_BUILDER_NO_PROXY
        - EXTERNAL_BUILDER_PEER_URL
  externalEndpoint: 'peer0.company.io:443'
  external_chaincode_builder: true
  gossip:
    bootstrap: ''
    endpoint: 'peer0.company.io:443'
    externalEndpoint: 'peer0.company.io:443'
    orgLeader: true
    useLeaderElection: false
  hosts:
    - peer0.company.io
  image: ghcr.io/kfsoftware/peer
  imagePullPolicy: IfNotPresent
  istio:
    hosts:
      - peer0.company.io
    ingressGateway: ''
    port: 443
  logging:
    cauthdsl: info
    gossip: info
    grpc: info
    ledger: info
    level: info
    msp: info
    peer: info
    policies: info
  mspID: KFSMSP
  replicas: 1
  resources:
    chaincode:
      limits:
        cpu: 100m
        memory: 56Mi
      requests:
        cpu: 10m
        memory: 28Mi
    couchdb:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
    peer:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 256Mi
  secret:
    enrollment:
      component:
        cahost: ca.company.io
        caname: ca
        caport: 443
        catls:
          cacert: >-
            <BASE64 TLS CERT OF THE CA>
        enrollid: peer
        enrollsecret: peerpw
      tls:
        cahost: ca.company.io
        caname: tlsca
        caport: 443
        catls:
          cacert: >-
            <BASE64 TLS CERT OF THE CA>
        csr:
          cn: peer0-company
          hosts:
            - 127.0.0.1
            - localhost
            - peer0.company.io
        enrollid: peer
        enrollsecret: peerpw
  service:
    type: NodePort
  serviceMonitor:
    enabled: true
    interval: 10s
    labels: {}
    sampleLimit: 0
    scrapeTimeout: 10s
  stateDb: couchdb
  storage:
    chaincode:
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClass: default
    couchdb:
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClass: default
    peer:
      accessMode: ReadWriteOnce
      size: 4Gi
      storageClass: default
  tag: v2.3.0-0.0.1

```

This is what the kubectl plugin creates in the cluster behind the scenes.

Note that in this case, the yaml specifies the stateDB in L126:
```yaml
  stateDb: couchdb
```

**Comment by rrozek** [comment] 2022-02-04 07:40
Hi. Let me highjjack this thread a little.
Using hlf operator, can we pull CRDs like the one you posted above somehow?
I mean, hlf operator does some stuff behind the scenes, but how can we inspect what was actually applied on the cluster?
Curious, because it seems calling 
```
kubectl hlf peer create --storage-class=standard \
    --enroll-id=peer --mspid=Org1MSP \
    --enroll-pw=peerpw --capacity=5Gi \
    --name=org1-peer0 --ca-name=org1-ca.default \
    --output > resources/org1/peer1.yaml
```
sends the output to `resources/org1/peer.yaml`
but what if during creation i didnt store that configuration, how can i re-get it?

Background:
i created a peer, but it has by default leveldb as db, and i need couchdb, so i need to remove a peer (`kubectl hlf peer delete --name <PUT NAME HERE>`) to recreate it later with couchdb param but i don't know where do i get the name from to delete it :)
assuming i created the peer using above provided command i would expect my peer is named `org1-peer0` which seems to be confirmed by
```
jrojek@jrojek-Latitude-5401:~$ kubectl get services
NAME                                              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                       AGE
...
org1-peer0                                        NodePort    XXXX      <none>        7051:30045/TCP,7052:31553/TCP,7053:30954/TCP,9443:31898/TCP   22d
org1-peer0-fs                                     ClusterIP   XXXX    <none>        8080/TCP                                                      22d

```

but then:
```
jrojek@jrojek-Latitude-5401:~$ kubectl hlf peer delete --name=org1-peer0.hyperledger
Error: fabricpeers.hlf.kungfusoftware.es "org1-peer0.hyperledger" not found
jrojek@jrojek-Latitude-5401:~$ kubectl hlf peer delete --name=org1-peer0
Error: fabricpeers.hlf.kungfusoftware.es "org1-peer0" not found
```
:( ( `.hyperledger` because that's our deployment namespace in cluster)

thank you!

**Comment by rrozek** [comment] 2022-02-04 08:22
Uhmpf... reading README wouldn't hurt i guess.
as in docs:
```
jrojek@jrojek-Latitude-5401:~$ kubectl delete fabricpeers.hlf.kungfusoftware.es --all-namespaces --all
fabricpeer.hlf.kungfusoftware.es "org1-peer0" deleted
```

**Comment by nkaramolegos** [comment] 2022-02-04 14:34
Thanks again. What about the transaction endorsement policies? How can I set majority (default) to all the orgs? Also, in case an organization has two peers what file should I configure in order one of the two peers to endorse the transaction?

**Comment by dviejokfs** [comment] 2022-02-05 11:29
@nkaramolegos 
When approving/committing chaincode, you can set the signaturePolicy, right now there's no way to set the default signaturePolicy of the channel.

You can see how to set up the endorsement policy: [https://kfsoftware.github.io/hlf-operator/docs/getting-started#approve-chaincode](https://kfsoftware.github.io/hlf-operator/docs/getting-started#approve-chaincode)

**Comment by nkaramolegos** [comment] 2022-02-07 08:55
Ok but how can set the majority rule as mentioned [here](https://hyperledger-fabric.readthedocs.io/en/release-2.2/policies.html#policy-types) in the ImplicitMetaPolicy? For example if have 3 orgs with 2 peers each one how can I set the policy to majority of orgs (i.e 2 of 3 orgs) and inside each org to set one of two peers (i.e peer 0 or peer1)?

**Comment by dviejokfs** [comment] 2022-02-09 09:01
Right now it's not possible, I have added an issue to include it in 1.5.0
https://github.com/kfsoftware/hlf-operator/issues/43

**Comment by nkaramolegos** [comment] 2022-02-09 10:46
Is there any workaround? When the 1.5.0 release is coming out?

**Comment by dviejokfs** [comment] 2022-02-10 16:55
Hi @nkaramolegos 
If you download the kubectl plugin for the release `v1.5.0-beta8`, we have added this feature in the branch feature/release-1.5

The release will be available in 10 minutes

**Comment by nkaramolegos** [comment] 2022-02-11 09:51
Thanks. I can not understand how the possible nil signature policy can help me. Can you give an example?

**Comment by dviejokfs** [comment] 2022-02-12 11:24
Hi @nkaramolegos 
If the endorsement policy is not set, the channel will use the default `Endorsement` policy defined; that's why using a nil signature policy to use the default.

You can see it in the HLF docs:
https://hyperledger-fabric.readthedocs.io/en/release-2.2/tutorial/commercial_paper.html?highlight=approveformyorg
![image](https://user-images.githubusercontent.com/84456338/153709267-6a0f11b2-aa94-40e0-a11b-6888776a6482.png)

**Comment by nkaramolegos** [comment] 2022-02-14 08:54
Of course. But the majority is the default policy for channel "mychannel" of the papernet network. For the channels created by hlf operator the default policy is the same? Where in the code is defined that? I need this in order to validate how the "vote" of an org arises (i.e in case of two peers we have 2 scenarios: 1. both to endorse, 2. one to endorse)

**Comment by dviejokfs** [comment] 2022-02-15 08:54
In this file is the default channel configured:
https://github.com/kfsoftware/hlf-operator/blob/540540774518c14a2c15ea75e1149f1021b2cdf7/controllers/testutils/channel.go#L205-L208

By default, it needs the majority of endorsements, and this depends on the number of organizations in the channel.

If you need to change or generate a custom channel, I recommend you to take that code and implement it in a custom GoLang API.

If you want to interact with the Kubernetes cluster, you can take a look at the [hlf-operator-api project](https://github.com/kfsoftware/hlf-operator-ui/blob/feature/prepare-release/api) and specifically at the query file to fetch peers, orderers and CAs from the Kubernetes cluster:
[https://github.com/kfsoftware/hlf-operator-ui/blob/feature/prepare-release/api/gql/resolvers/query.go](https://github.com/kfsoftware/hlf-operator-ui/blob/feature/prepare-release/api/gql/resolvers/query.go)

**Comment by nkaramolegos** [comment] 2022-02-16 10:23
Thank you for the API reference. So the `channel.go` file describes which is the default policy for every channel I create using the plugin tool. In case I need to change the default policy I have to pass the appropriate argument. Correct?

**Comment by nkaramolegos** [comment] 2022-02-23 12:34
So In a scenario where I am extreme paranoid and I have two orgs with 2 peers each one and want every peer to endorse I can use AND(AND('Org1.peer', 'Org1.peer'), AND('Org2.peer', 'Org2.peer')) using the --policy flag

**Comment by dviejokfs** [comment] 2022-02-26 06:46
Hi @nkaramolegos,

I haven't tried that policy config, not sure if it will require endorsement from 2 peers from org1 and 2 peers from org2.

But in that case, the network will depend on one than more peer from the org1 and org2, which can cause your network to not work in case there are problems with any of those peers.

**Comment by dviejokfs** [comment] 2022-02-26 06:46
I'm closing the issue since the documentation is already published:

https://kfsoftware.github.io/hlf-operator/docs/operator-guide/state-db

**Closed as completed by dviejokfs** 2022-02-26 06:47 UTC
